#!/user/mojedasa/python/Python-2.7.11/python

import sys
import time
if len(sys.argv) < 2:
	print "Argument missing: slotNumber"
        print "e.g.: ", sys.argv[0], "5"
	exit(0)
else:
	msg = "MasterDDS is in slot " + str(int(sys.argv[1])) + "? (y/n)"
        if raw_input(msg) != 'y':
                print "Canceled."
                exit(0)


slot = int(sys.argv[1])
# import mdds
# mod = mdds.mdds(slot)

import spsFreqProgDDS
m = spsFreqProgDDS.Module.slot(slot)

print '========================================'

if int(sys.argv[2]) == 1:
        print 'disable'
        m.mddsLPFControl = 0x4040 # DO disable the filter, bit6
else:
        print 'ena'
        m.mddsLPFControl = 0x4000 # do NOT disable the filter, bit6






