#!/user/mojedasa/python/Python-2.7.11/python

import sys
import time
if len(sys.argv) < 2:
	print "Argument missing: slotNumber"
        print "e.g.: ", sys.argv[0], "5"
	exit(0)
else:
	msg = "MasterDDS is in slot " + str(int(sys.argv[1])) + "? (y/n)"
        if raw_input(msg) != 'y':
                print "Canceled."
                exit(0)

if len(sys.argv) != 3:
	print "Argument missing: value"
	exit(0)

import mdds
slot = int(sys.argv[1])
mod = mdds.mdds(slot)

# import spsFreqProgDDS
# m = spsFreqProgDDS.Module.slot(slot)


print '========================================'
g = int(sys.argv[2])
print 'gain = ', g
mod.setADCGain(g)
print 'done.'





