#!/bin/csh
setenv FEC_RADICAL cfv-sr4-
alias printError 'set ev = $status && echo "error :" + $ev && exit $ev'

echo ""
echo "Make bin.old.v7 on SR4 frontends. "
echo "=================================="
echo ""
foreach FEC_EXT (adthb1 adthb2 adtvb1 adtvb2 allbc2b1 allbc2b2 allsync3 apwb1 apwb2)
	echo ""
	echo $FEC_RADICAL$FEC_EXT
	echo "-----------------"
	echo ""
	pushd `pwd`
		cd /acc/dsc/lhc/$FEC_RADICAL$FEC_EXT/bin || printError
		cp ALLVTU_R.old ALLVTU_R.old.$1
		cp ALLVTU_S.old ALLVTU_S.old.$1
	popd
end

