#!/bin/csh
setenv FEC_RADICAL cfv-ba3-
alias printError 'set ev = $status && echo "error :" + $ev && exit $ev'

echo ""
echo "Dtab on BA3 frontends. "
echo "=================================="
echo ""
foreach FEC_EXT (allion1 allproton1 alldiag1 allbc1 allsync1)
	echo ""
	echo $FEC_RADICAL$FEC_EXT
	echo "-----------------"
	echo ""
	pushd `pwd`
		cd /acc/dsc/src/sps/$FEC_RADICAL$FEC_EXT/ || printError
		yes | make transfer.ref -j 10
		yes | make new_dtab -j 10
	popd
end

