#!/user/mojedasa/python/Python-2.7.11/python

import sys
import time
if len(sys.argv) != 2:
	print "Argument missing: slotNumber"
        print "e.g.: ", sys.argv[0], "6"
	exit(0)
else:
	msg = "MasterDDS is in slot " + str(int(sys.argv[1])) + "? (y/n)"
        if raw_input(msg) != 'y':
                print "Canceled."
                exit(0)



import sdds
slot = int(sys.argv[1])
mod = sdds.sdds(slot)

print '========================================'
print 'Initialize SlaveDDS'
mod.init_module()


