# Generated by "./init_mdds" on 16.10.10 15:18

# A script to setup a MasterDDS module 
#
# To generate f_out =  354630882.619 Hz (FTW_out = 0x35922dd6)
# - The module needs to receive (over backplane SerDes) an FTW value = 0x1999999a
# - ADC gain set to zero


if [ $# -eq 0 ]; 
    then echo "enter the slot number!"
    exit
fi
MasterSlot=$1

cmd="writevme "$MasterSlot"0022a 1 0200"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00200 1 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00202 1 ff9c"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00204 2 000f 3b38"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00208 2 36e1 cb6e"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00210 2 62f6 e99d"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"0020c 2 0000 1c5f"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00012 1 0400"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 00f0"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00000 1 0202"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00000 1 0101"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00000 1 0202"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0010"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0001"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0002"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0300"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0003"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 358e 2196"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0004"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0020"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0001"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0000"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0002"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 0000 0301"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0003"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00040 2 358e 2196"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00044 1 0004"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00000 1 0202"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00012 1 0404"
echo $cmd
$cmd

cmd="writevme "$MasterSlot"00200 1 0000"
echo $cmd
$cmd

