#!/user/mojedasa/python/Python-2.7.11/python

import sys
import time
if len(sys.argv) < 3:
	print "Argument missing: slotNumber"
        print "e.g.: ", sys.argv[0], "5"
	exit(0)
else:
	msg = "MasterDDS is in slot " + str(int(sys.argv[1])) #+ "? (y/n)"
        # if raw_input(msg) != 'y':
        #         print "Canceled."
        #         exit(0)



from subprocess import Popen, PIPE
def rd_vme(addr_s, n=2, verbose=True):
         p = Popen(['read_vme', '-w16', '-a480000', '-l'+str(n)], stdin=PIPE, stdout=PIPE, stderr=PIPE)
         output, err = p.communicate()
         d = list()
         sa = output.split('\n')
         for i in range(len(sa)/2):
                 msw = int(sa[i],16)
                 lsw = int(sa[i+1],16)
                 dw = (msw<<16 | lsw)
                 print 'dw = ', hex(dw)
                 d.append(dw)

         return d




slot = int(sys.argv[1])
import spsFreqProgDDS
m = spsFreqProgDDS.Module.slot(slot)

print 'acq status   = ', hex(m.acqStatus)
print 'acq frzaddr  = ', m.acqFrzAddr
print 'acq control  = ', m.acqControl

addr = '0x'+str(slot)+'%05x'%(0x80000)
print 'a = ', hex(int(addr))
buf = rd_vmw(addr)

#print 'd     = ', buf
print 'len(buf) = ', len(buf)

f = open('dump', 'w')
for i in range(len(buf)):
        val = buf[i]
        f.write(str(val)+'\n')
        
f.close()

print 'Done'

