# Generated by "./init_mdds" on 16.11.04 09:59

# A script to setup a MasterDDS module 
#
# To generate f_out =  354630882.619 Hz (FTW_out = 0x35922dd6)
# - The module needs to receive (over backplane SerDes) an FTW value = 0x1999999a
# - ADC gain set to zero


if [ $# -eq 0 ]; 
    then echo "enter the slot number!"
    exit
fi
MasterSlot=$1

